server:
  port: 8080

spring:
  application:
    name: server-gateway-8080
  cloud:
    gateway:
      routes:
        - id: product-gateway-server-8080
#          uri: http://127.0.0.1:8004      #静态路由
          uri: lb://product-provider       #动态路由，通过服务名来匹配服务
          predicates:
          - Path=/product/**
          filters:
          #重写路由
          - RewritePath=/gateway-product/(?<segment>.*), /$\{segment}
          - name: RequestRateLimiter
            args:
              # 使用SpEL从容器中获取对象
              key-resolver: '#{@PathKeyResolver}'
              # 令牌桶每秒填充平均速率
              redis-rate-limiter.replenishRate: 1
              # 令牌桶的总容量
              redis-rate-limiter.burstCapacity: 3
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
