server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: consumer-feign

feign:
  client:
    config:
      PRODUCT-PROVIDER:
        loggerLevel: FULL
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'